services:
  web:
    image: jgarber623/flight-manual-atom-editor-cc-web
    build:
      context: .
    container_name: flight-manual-atom-editor-cc-web
    entrypoint: tail -f /dev/null
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        consistency: delegated
      - type: volume
        target: /usr/src/dependencies

networks:
  default:
    name: flight-manual-atom-editor-cc-web-network
