name: CI

on: push

env:
  CI: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: npm
      - run: npm ci
      - run: script/cibuild
